//
// Created by Pratham Jaiswal on 20/03/24.
//

#ifndef RFID_READER_TASKS_COMMON_H
#define RFID_READER_TASKS_COMMON_H

#include "freertos/FreeRTOSConfig.h"

#define APP_STATE_DISP_TASK_NAME "app_el"
#define APP_STATE_DISP_TASK_QUEUE_SIZE 10
#define APP_STATE_DISP_TASK_STACK_SIZE 4096
#define APP_STATE_DISP_TASK_PRIORITY (configMAX_PRIORITIES - 1)
#define APP_STATE_DISP_TASK_CORE_ID 0

#define BLE_APP_TASK_NAME "ble_el"
#define BLE_APP_TASK_QUEUE_SIZE 10
#define BLE_APP_TASK_STACK_SIZE 4096
#define BLE_APP_TASK_PRIORITY (configMAX_PRIORITIES - 2)
#define BLE_APP_TASK_CORE_ID 0

#define WIFI_APP_TASK_NAME "wifi_el"
#define WIFI_APP_TASK_QUEUE_SIZE 10
#define WIFI_APP_TASK_STACK_SIZE 4096
#define WIFI_APP_TASK_PRIORITY (configMAX_PRIORITIES - 2)
#define WIFI_APP_TASK_CORE_ID 0

#define HTTP_SERVER_TASK_STACK_SIZE 8192
#define HTTP_SERVER_TASK_PRIORITY (WIFI_APP_TASK_PRIORITY - 1)
#define HTTP_SERVER_TASK_CORE_ID 0

#define USB_APP_TASK_NAME "usb_el"
#define USB_APP_TASK_STACK_SIZE 4096
#define USB_APP_TASK_PRIORITY (configMAX_PRIORITIES - 2)
#define USB_APP_TASK_CORE_ID 0

#define UART_COMM_TASK_STACK_SIZE 8192
#define UART_COMM_TASK_PRIORITY (configMAX_PRIORITIES - 2)
#define UART_COMM_TASK_CORE_ID 1

#define COMM_INTERFACE_TASK_QUEUE_SIZE 10
#define COMM_INTERFACE_TASK_NAME "comm_el"
#define COMM_INTERFACE_TASK_STACK_SIZE 8192
#define COMM_INTERFACE_TASK_PRIORITY (configMAX_PRIORITIES - 3)
#define COMM_INTERFACE_TASK_CORE_ID 1

#define RFID_MODULE_TASK_NAME "rfid_el"
#define RFID_MODULE_TASK_QUEUE_SIZE 10
#define RFID_MODULE_TASK_STACK_SIZE 8192
#define RFID_MODULE_TASK_PRIORITY (configMAX_PRIORITIES - 3)
#define RFID_MODULE_TASK_CORE_ID 1

#define BMS_TASK_STACK_SIZE 4096
#define BMS_TASK_PRIORITY (configMAX_PRIORITIES - 5)
#define BMS_TASK_CORE_ID 1

#define TEMP_TASK_STACK_SIZE 2048
#define TEMP_TASK_PRIORITY (configMAX_PRIORITIES - 10)
#define TEMP_TASK_CORE_ID 1

#endif //RFID_READER_TASKS_COMMON_H
